image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - master
  artifacts:
    untracked: true
  script:
    - node --version
    - cd website
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod # --base-href accounts.weavver.com
#    - ./node_modules/@angular/cli/bin/ng test --progress false --single-run=true --watch=false
#    - ./node_modules/@angular/cli/bin/ng e2e --progress false --watch=false
  artifacts:
    paths:
      - website/dist/*

test:
  stage: test
  script:
    - echo $CI_JOB_STAGE # calls a predefined variable
    - echo $TEST
    - cd api
    - npm install
    - npm install -g mocha
    - mocha {,!(node_modules)/**}/*.test.js

deploy:
  image: mesosphere/aws-cli:1.14.5
  only:
    - master
  dependencies:
    - build
  script:
    - aws s3 sync website/dist s3://weavver-accounts --delete --acl public-read
    - aws cloudfront create-invalidation --distribution-id E3QVJ7D556DGGR --paths "/*"